package chapter.six.two.one.one

import org.junit.jupiter.api.Test

internal class CatchExceptionTest {
    @Test
    fun maintest() {
        CatchException.main(arrayOf())
    }
}