package chapter.six.three.one.one

import org.junit.jupiter.api.Test

internal class ExceptionCatchTest {
    @Test
    fun maintest() {
        ExceptionCatch.main(arrayOf())
    }
}